### ISSUE TITLE
X-Client-Uuid not showing up

### ISSUE THREAD

**Issue by jattak47** [Lyfhael/DeleteTweets#10]
![image](https://github.com/Lyfhael/DeleteTweets/assets/113661114/c80431f3-f1a4-4dda-ae67-0a7f15ba7df7)

Checked a bunch of entries & there's no Uuid which is strange since I used the script last week.

**Comment by Lyfhael** [comment]
If you can't find a Uuid, you can put a random value instead of it, it will still work.
