### ISSUE TITLE
Removing RTs?

### ISSUE THREAD

**Issue by shaunduke** [Lyfhael/DeleteTweets#11]
Is this script meant to remove RTs, or is that a function that is not yet built in OR that has to be toggled somewhere? 

Apologies if this is not the correct way to do this. It is exactly my second post on a GitHub thing. Thank you for the script, though. It is beautiful.

**Comment by Lyfhael** [comment]
> Is this script meant to remove RTs, or is that a function that is not yet built in OR that has to be toggled somewhere?
> 
> Apologies if this is not the correct way to do this. It is exactly my second post on a GitHub thing. Thank you for the script, though. It is beautiful.

explained here :
https://github.com/Lyfhael/DeleteTweets#filtering--options

> Edit 29/08/2023, you can now choose to also unretweet or not, by changing the "unretweet" property in the delete_options variable. Set it to true if you want to unretweet. It combines with the other filters.
