### ISSUE TITLE
Guidance on Rate Limiting

### ISSUE THREAD

**Issue by chrisrosa** [Lyfhael/DeleteTweets#12]
I'm curious to hear your experience and recommended approach re: rate limiting. I hit the wall at approximately 5 mins.

**Comment by f0rkth1s** [comment]
I have just managed to clear my entire account's posts and retweets without hitting the limit. Took an hour or so.

**Comment by Lyfhael** [comment]
You may hit the threshold, the script will handle it and try to resume every minute. After a few retries it should work again.
If you it retries and after 10+ minutes it hasn't resumed at all, then retry 1 hour later, then 1 day later.

In general you should be able to delete about 3000+ tweets per day, even if you hit a few ratelimits the script will resume.
