### ISSUE TITLE
doesn't delete threads

### ISSUE THREAD

**Issue by eclipsebykimplip** [Lyfhael/DeleteTweets#15]
my page looks empty but it says that i still have over 4000 tweets. when i log onto another account and look at the page i can see some of the tweets and i realize that they're all replies to myself. the original tweets are gone but the rest of the threads are still there.

**Comment by Lyfhael** [comment]
Could you tell me your @, here or in DM if you prefer. So I can see exactly how the response object is formatted to see why it didn't catch these tweetss
