### ISSUE TITLE
feature request: don't delete pinned tweet

### ISSUE THREAD

**Issue by ex-nerd** [Lyfhael/DeleteTweets#16]
I'd like to keep around an "I delete tweets" pinned tweet.

**Comment by ex-nerd** [comment]
I suppose this can be handled with the "don't delete <id>", but might still be nice to have an override that doesn't require finding the id of whatever pinned tweet is there at the time.

**Comment by Lyfhael** [comment]
I added the option, "do_not_remove_pinned_tweet" is set to true by default in the delete_options
