### ISSUE TITLE
Retweets and likes

### ISSUE THREAD

**Issue by PLMBakery** [Lyfhael/DeleteTweets#19]
would be nice to add the feature or new tool for delete retweets and likes

**Comment by Peteous** [comment]
Yes, I would also appreciate the ability to remove likes

**Comment by Lyfhael** [comment]
> would be nice to add the feature or new tool for delete retweets and likes

There's already an option to remove the retweets, read the description ;)

As for the like there's another tool I made: https://github.com/Lyfhael/UnlikeAllTweets
