### ISSUE TITLE
Add unlike option

### ISSUE THREAD

**Issue by Aleatoirement** [Lyfhael/DeleteTweets#20]
Would it be possible to add an option to unlike tweets? 

Thank you! And thank you for your awesome JS! It helped me a lot!

**Comment by Spottyfriend** [comment]
Would also massively appreciate this, since part of the point of deleting all tweets regularly is for privacy/security. That doesn't work so well if someone can still see your likes going back years. This project is extremely helpful nonetheless!

**Comment by Lyfhael** [comment]
I've another project that does this : https://github.com/Lyfhael/UnlikeAllTweets :)
