### ISSUE TITLE
x-client-uuid no longer exists

### ISSUE THREAD

**Issue by zooool** [Lyfhael/DeleteTweets#27]
x-client-uuid or "client_uuid" can no longer be retrieved from any file Twitter serves.

**Comment by roshanmirajkar** [comment]
log-in to twitter and you can find it in ANY response headers in Fetch/XHR

**Comment by zooool** [comment]
> log-in to twitter and you can find it in ANY response headers in Fetch/XHR

Sadly that header does not exist anymore.

**Comment by roshanmirajkar** [comment]
that is not true.

- what browser are you using?
<img width="677" alt="GitHubExample" src="https://github.com/Lyfhael/DeleteTweets/assets/16927460/b48336ae-b5d8-46b5-96a1-12d468ac52e2">

**Comment by Lyfhael** [comment]
Hey, put any value it'll work

**Comment by FirstVoyager** [comment]
> that is not true.
> 
> * what browser are you using?
> 
> <img alt="GitHubExample" width="677" src="https://private-user-images.githubusercontent.com/16927460/292686460-b48336ae-b5d8-46b5-96a1-12d468ac52e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDUxMTQsIm5iZiI6MTcyMjYwNDgxNCwicGF0aCI6Ii8xNjkyNzQ2MC8yOTI2ODY0NjAtYjQ4MzM2YWUtYjVkOC00NmI1LTk2YTEtMTJkNDY4YWM1MmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEzMjAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MmQ3MjU0ZGFhYmVkYTUxMDBhNTVjYWY5YjY3MGUwZjdkNzQ2ODEwYzdmZTBlNTc3ZjRmZDkxMWY3YzZiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2asKawJJipK6kFenguXjknxLR9zTabmdE6VR3r9EtYc">

is there any way to get uuid etc via js code?
