### ISSUE TITLE
Removing likes in the same way

### ISSUE THREAD

**Issue by berkantkz** [Lyfhael/DeleteTweets#38]
Hi,

This is actually not an issue but an idea. I am wondering if we can achieve the same thing to remove likes using ```https://twitter.com/i/api/graphql/ZYKSe-w7KEslx3JhSIk5LA/UnfavoriteTweet``` api.

Best regards.

**Comment by Lyfhael** [comment]
Hi,

I did a project like this before : https://github.com/Lyfhael/UnlikeAllTweets

Multiple issues if there are too many likes : 
- You may not see them anymore in your Likes tab, but they will appear for other
- Everyone may not see them anymore and they will still reappear a few hours/days later

It seems like Twitter wants  to make it very hard for people  to remove them.
Sometime it works tho.

**Comment by berkantkz** [comment]
That does the job. Thank you so much!
