### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Thund3rstruck** [Lyfhael/DeleteTweets#6]
VM368:124 Uncaught TypeError: entries is not iterable
    at log_tweets (anonymous:123:19)
    at anonymous:266:15

Unsure what caused this; acquired all variables as intended and nothing came of it.
Each instance of anonymous was wrapped in <>s. Unsure if this necessary information.

**Comment by teisseire117** [comment]
> VM368:124 Uncaught TypeError: entries is not iterable at log_tweets (anonymous:123:19) at anonymous:266:15
> 
> Unsure what caused this; acquired all variables as intended and nothing came of it. Each instance of anonymous was wrapped in <>s. Unsure if this necessary information.

Hi, try this : https://github.com/teisseire117/DeleteTweets#uncaught-typeerror-entries-is-not-iterable
It shows a fix if you have this issue. Also get the last version of the script :)
