### ISSUE TITLE
Script stops after a certain time

### ISSUE THREAD

**Issue by baktelraalis** [Lyfhael/DeleteTweets#76]
I'm trying to delete 50k tweets, which may be a lot. At some point the script stops I think because the API has reached its limit :( 
The error encountered is “Rate limit reached. Waiting 1 minute”. 
GET 429 (Too Many Requests)
In my opinion, there's now a limitation in this way... 
Any way to counter this?
Merci !

**Comment by n3wjack** [comment]
It should continue after a few minutes. You can just let it run and at some point it's going to start deleting tweets again.

**Comment by justex07** [comment]
I am having this same issue when it hits around 16k tweets deleted. The error I receive is "Debugging connection was closed. Reason: Render process gone. Reconnect when ready by reopening DevTools."
![Google Chrome-DevTools - x comhome-2024-11-15 at 13 51 48@2x](https://github.com/user-attachments/assets/91b35a58-c885-4e9e-9b0e-9ec0f86f4b62)

**Comment by baktelraalis** [comment]
Thanks @n3wjack 

I finally used the method to send my tweets.js file and it worked up to a point (I have 50k tweets to clear).

I think the script isn't working at the moment I just have a long list of 228/11771 going on, running without deleting anything... 

Merci.

**Comment by baktelraalis** [comment]
@n3wjack 

As you answered in another ticket here, I enabled the unretweet action and it seems to be going ahead, that was probably it, I'll see :) 

Merci.
