### ISSUE TITLE
Suggestion: Language check

### ISSUE THREAD

**Issue by yourlocalanimeboy** [Lyfhael/DeleteTweets#9]
In async function delete_tweets, you set client language as fr. You can remind us to change it or make that string a variable that we can fill (and define widespread languages like english, french, german etc) 

And good news. It works well in any chromium based browser. Just don't exceed 3750 tweets/day and no one gets banned

**Comment by Lyfhael** [comment]
> In async function delete_tweets, you set client language as fr. You can remind us to change it or make that string a variable that we can fill (and define widespread languages like english, french, german etc)
> 
> And good news. It works well in any chromium based browser. Just don't exceed 3750 tweets/day and no one gets banned

What is the source for the 3750 tweets/day ? Does exceeding it 100% result in a ban ?
For the language it should be automatic now
